version: "3.0"
services:
  frontend:
    container_name: client
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql